server:
    port: 9080
    servlet:
        context-path: /springboot-demo  #访问地址加入项目名  http://localhost:9080/springboot-demo/xx
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver

    #mail sender settings
    mail:
        host: 10.135.1.238
        username: aiservice@haier.net
        password:
        properties:
            mail:
                smtp:
                    auth: true
        freemarker: #编码格式
            charset: UTF-8
        template:
            active: template.ftl

    freemarker:
        cache: false #缓存配置
        expose-request-attributes: false
        content-type: text/html
        template-loader-path: classpath:/templates/
        expose-spring-macro-helpers: false
        check-template-location: true
        enabled: true

logging:
    level:
        ROOT: info
        com.hshbic.ai: debug
    file: logs/ai-mail-service.log

    #文件上传路径
path:
    uploadPath: /data/upload
    downloadPath: /data/download


# mybatis 配置
mybatis:
    type-aliases-package: com.hshbic.ai.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    mapper:
        mappers: com.hshbic.ai.dao
        not-empty: false
        identity: MYSQL




